version: '0.1-{build}'

os: Visual Studio 2015
platform: x64
test: off

configuration: release

cache:
  - build\SDL2 -> .gitmodules
  - build\freetype2 -> .gitmodules
  - build\libnoise -> .gitmodules
  - build\assimp -> .gitmodules

init:
  - cmd: git config --global lfs.fetchexclude "*"

before_build:
  - cmd: git submodule update --init --recursive
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha11/premake-5.0.0-alpha11-windows.zip' 'premake.zip'
    # Extract it in-place; premake5.exe is at the top level.
  - 7z x premake.zip
  - cmd: premake5 vs2015

build:
  parallel: true
  project: build/planet.sln

install:
 - set COMMIT_SHA=%APPVEYOR_REPO_COMMIT:~0,8%

artifacts:
 - path: bin
   name: 'planet-v0.1-$(COMMIT_SHA)_win64'
   type: zip