# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.1_1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.1_1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/eugene.sturm/projects/misc/planet72

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/eugene.sturm/projects/misc/planet72

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.1_1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.1_1/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eugene.sturm/projects/misc/planet72/CMakeFiles /Users/eugene.sturm/projects/misc/planet72/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/eugene.sturm/projects/misc/planet72/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dg

# Build rule for target.
dg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dg
.PHONY : dg

# fast build rule for target.
dg/fast:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/build
.PHONY : dg/fast

App.o: App.cpp.o
.PHONY : App.o

# target to build an object file
App.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/App.cpp.o
.PHONY : App.cpp.o

App.i: App.cpp.i
.PHONY : App.i

# target to preprocess a source file
App.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/App.cpp.i
.PHONY : App.cpp.i

App.s: App.cpp.s
.PHONY : App.s

# target to generate assembly for a file
App.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/App.cpp.s
.PHONY : App.cpp.s

Camera.o: Camera.cpp.o
.PHONY : Camera.o

# target to build an object file
Camera.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/Camera.cpp.o
.PHONY : Camera.cpp.o

Camera.i: Camera.cpp.i
.PHONY : Camera.i

# target to preprocess a source file
Camera.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/Camera.cpp.i
.PHONY : Camera.cpp.i

Camera.s: Camera.cpp.s
.PHONY : Camera.s

# target to generate assembly for a file
Camera.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/Camera.cpp.s
.PHONY : Camera.cpp.s

DebugRenderer.o: DebugRenderer.cpp.o
.PHONY : DebugRenderer.o

# target to build an object file
DebugRenderer.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/DebugRenderer.cpp.o
.PHONY : DebugRenderer.cpp.o

DebugRenderer.i: DebugRenderer.cpp.i
.PHONY : DebugRenderer.i

# target to preprocess a source file
DebugRenderer.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/DebugRenderer.cpp.i
.PHONY : DebugRenderer.cpp.i

DebugRenderer.s: DebugRenderer.cpp.s
.PHONY : DebugRenderer.s

# target to generate assembly for a file
DebugRenderer.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/DebugRenderer.cpp.s
.PHONY : DebugRenderer.cpp.s

Frustum.o: Frustum.cpp.o
.PHONY : Frustum.o

# target to build an object file
Frustum.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/Frustum.cpp.o
.PHONY : Frustum.cpp.o

Frustum.i: Frustum.cpp.i
.PHONY : Frustum.i

# target to preprocess a source file
Frustum.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/Frustum.cpp.i
.PHONY : Frustum.cpp.i

Frustum.s: Frustum.cpp.s
.PHONY : Frustum.s

# target to generate assembly for a file
Frustum.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/Frustum.cpp.s
.PHONY : Frustum.cpp.s

SystemSDL2.o: SystemSDL2.cpp.o
.PHONY : SystemSDL2.o

# target to build an object file
SystemSDL2.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/SystemSDL2.cpp.o
.PHONY : SystemSDL2.cpp.o

SystemSDL2.i: SystemSDL2.cpp.i
.PHONY : SystemSDL2.i

# target to preprocess a source file
SystemSDL2.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/SystemSDL2.cpp.i
.PHONY : SystemSDL2.cpp.i

SystemSDL2.s: SystemSDL2.cpp.s
.PHONY : SystemSDL2.s

# target to generate assembly for a file
SystemSDL2.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/SystemSDL2.cpp.s
.PHONY : SystemSDL2.cpp.s

gfx/gl/GLRenderDevice.o: gfx/gl/GLRenderDevice.cpp.o
.PHONY : gfx/gl/GLRenderDevice.o

# target to build an object file
gfx/gl/GLRenderDevice.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/gfx/gl/GLRenderDevice.cpp.o
.PHONY : gfx/gl/GLRenderDevice.cpp.o

gfx/gl/GLRenderDevice.i: gfx/gl/GLRenderDevice.cpp.i
.PHONY : gfx/gl/GLRenderDevice.i

# target to preprocess a source file
gfx/gl/GLRenderDevice.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/gfx/gl/GLRenderDevice.cpp.i
.PHONY : gfx/gl/GLRenderDevice.cpp.i

gfx/gl/GLRenderDevice.s: gfx/gl/GLRenderDevice.cpp.s
.PHONY : gfx/gl/GLRenderDevice.s

# target to generate assembly for a file
gfx/gl/GLRenderDevice.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/gfx/gl/GLRenderDevice.cpp.s
.PHONY : gfx/gl/GLRenderDevice.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/main.cpp.s
.PHONY : main.cpp.s

stdafx.o: stdafx.cpp.o
.PHONY : stdafx.o

# target to build an object file
stdafx.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/stdafx.cpp.o
.PHONY : stdafx.cpp.o

stdafx.i: stdafx.cpp.i
.PHONY : stdafx.i

# target to preprocess a source file
stdafx.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/stdafx.cpp.i
.PHONY : stdafx.cpp.i

stdafx.s: stdafx.cpp.s
.PHONY : stdafx.s

# target to generate assembly for a file
stdafx.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/stdafx.cpp.s
.PHONY : stdafx.cpp.s

utilities/File.o: utilities/File.cpp.o
.PHONY : utilities/File.o

# target to build an object file
utilities/File.cpp.o:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/utilities/File.cpp.o
.PHONY : utilities/File.cpp.o

utilities/File.i: utilities/File.cpp.i
.PHONY : utilities/File.i

# target to preprocess a source file
utilities/File.cpp.i:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/utilities/File.cpp.i
.PHONY : utilities/File.cpp.i

utilities/File.s: utilities/File.cpp.s
.PHONY : utilities/File.s

# target to generate assembly for a file
utilities/File.cpp.s:
	$(MAKE) -f CMakeFiles/dg.dir/build.make CMakeFiles/dg.dir/utilities/File.cpp.s
.PHONY : utilities/File.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... dg"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... App.o"
	@echo "... App.i"
	@echo "... App.s"
	@echo "... Camera.o"
	@echo "... Camera.i"
	@echo "... Camera.s"
	@echo "... DebugRenderer.o"
	@echo "... DebugRenderer.i"
	@echo "... DebugRenderer.s"
	@echo "... Frustum.o"
	@echo "... Frustum.i"
	@echo "... Frustum.s"
	@echo "... SystemSDL2.o"
	@echo "... SystemSDL2.i"
	@echo "... SystemSDL2.s"
	@echo "... gfx/gl/GLRenderDevice.o"
	@echo "... gfx/gl/GLRenderDevice.i"
	@echo "... gfx/gl/GLRenderDevice.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stdafx.o"
	@echo "... stdafx.i"
	@echo "... stdafx.s"
	@echo "... utilities/File.o"
	@echo "... utilities/File.i"
	@echo "... utilities/File.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

